### ISSUE TITLE
Ability to dynamically toggle the "disabled" prop

### ISSUE THREAD

**Issue by Banjerr** [erichbehrens/react-animated-slider#46]
Howdy,

I'm attempting to use this great component for a project, but one thing that I haven't been able to figure out is a way to dynamically toggle the "disabled" prop. My use case is this... every "slide" contains a question, which I would like to have "required" before the user can move to the next slide. I've attempted passing a function to the `disabled` prop, but it appears that only accepts a boolean value. Anyone know of a possible work around for this?

Thanks!

**Comment by erichbehrens** [comment]
Hi, I think you'd better handle this in the parent component. When the user gives the answer you could update the local state, which would trigger a rerender of the slider with the new value for the disabled prop. Even if the prop would accept functions you'd still have to store the answer value somewhere in the parent component in order to make the function call work.

Another thing you need to think of is resetting the disabled value after the user navigates to the new slide. This can be done passing a function to `onSlideChange`.

**Comment by Banjerr** [comment]
that makes sense @erichbehrens thanks

i actually ended up not using this component for that particular project; but definitely plan to use this on others, thanks for the great work!
