### ISSUE TITLE
Slide with tab key, is it possible?

### ISSUE THREAD

**Issue by Pifko6** [erichbehrens/react-animated-slider#87]
Suppose I have a slider with multiple 'cards'. Each card has input fields, <input> tag. Is there a way to slide with tab key, if I defined tabindex for individual field? For example if I select last input field with a tab key, and press it again, will  slider change on the next 'page'. If possible also with infinitive slider.

Sorry for my English.

**Comment by erichbehrens** [comment]
Hi, this is an interesting use case! Here you can find a basic implementation: https://codesandbox.io/s/3zoykpkz5

There are still a few issues to address:
- after navigating to the next slide the UI will blink. Maybe it can be prevented by manually setting the focus to the next element after the animation. This does not happen if you use `event.preventDefault()`
- pressing tab on the last slide will not focus the element on the first slide. Can be fixed by manually setting focus to that element (maybe using same fix for the previous point)

PS: I keep it in English as it can be useful for others, but... lep pozdrav! :)

**Comment by Pifko6** [comment]
> Hi, this is an interesting use case! Here you can find a basic implementation: https://codesandbox.io/s/3zoykpkz5
> 
> There are still a few issues to address:
> 
>     * after navigating to the next slide the UI will blink. Maybe it can be prevented by manually setting the focus to the next element after the animation. This does not happen if you use `event.preventDefault()`
> 
>     * pressing tab on the last slide will not focus the element on the first slide. Can be fixed by manually setting focus to that element (maybe using same fix for the previous point)
> 
> 
> PS: I keep it in English as it can be useful for others, but... lep pozdrav! :)

Will it also work if I have three cards on a single slider page?

**Comment by erichbehrens** [comment]
In this case your js code should also know how many cards are displayed. You could add a `data-card-index` attribute to the last field of each card and in the event handler you can check if it was triggered by the last displayed card

```js
if (event.target.getAttribute('data-card-index') % displayedCards === 0) {
// go to next slide
}
```

or

you could only assign `onKeyDown={this.handleKeyDown}` to the last visible card using a similar logic as above.
